#!/bin/bash

# define directories
origin=`cd $(dirname $0);pwd `
exec_dir="$origin/exec"
service_dir="$origin/service"
working_dir="/etc/ddns"
system_service="/etc/systemd/system"

# tools part 
Usage() {
    echo "Usage: ./$0 { config | clean | start | stop } [conf] | status"
    echo "[conf] : the name of you configure(without '.conf')."
    exit 1
}

Parameter_judge() {
    correct_num=$1
    real_num=$2
    if [ $correct_num != $real_num ];then
        Usage
    fi
}

Print_RED() {
	RED='\033[0;31m'
	NC='\033[0m'
	echo -e "${RED}$1${NC}"
}

Get_PID() {
    conf="$1"
    PID=`sudo ps aux | grep noip | grep $conf | awk -F ' ' '{print $2}'`
    if [ "$PID" = " " ];then
        PID="Not Running" 
    fi
    echo $PID
}

# main part 
Config() {
    conf="$1"
    sudo mkdir -p $working_dir 

    # copy noip exec to /etc/ddns
    sudo cp $exec_dir/noip2-x86_64 $working_dir/

    # config service execuable script
    sudo cp $exec_dir/ddns.sh.template $working_dir/ddns-$conf.sh
    sudo sed -i "s/NOIP-CONF/$conf/g" $working_dir/ddns-$conf.sh
    sudo chmod +x $working_dir/ddns-$conf.sh

    # generate noip config 
    $exec_dir/noip2-x86_64 -C -c $conf.conf
    sudo mv $conf.conf $working_dir/

    # config service
    sudo cp $service_dir/ddns.service.template $system_service/ddns-$conf.service
    sudo sed -i "s/CONF/$conf/g" $system_service/ddns-$conf.service
    
    # config timer
    sudo cp $service_dir/ddns.timer.template $system_service/ddns-$conf.timer
    sudo sed -i "s/CONF/$conf/g" $system_service/ddns-$conf.timer
}

Clean() {
    conf="$1"
    Print_RED "clean the configure of $conf"
    # remove service configure
    sudo rm $system_service/ddns-$conf.service 
    sudo rm $system_service/ddns-$conf.timer

    # remove configure
    sudo rm $working_dir/$conf.conf
    sudo rm $working_dir/ddns-$conf.sh

    # remove /etc/ddns when there is no configure in it
    ls /etc/ddns/ | grep ddns || sudo rm -r /etc/ddns/

    # remove auto generate files "NO-IP*"
    rm $origin/NO-IP* > /dev/null 2>&1 
}

Start() {
    conf="$1"
    Print_RED "start ddns $conf"
    for cmd in start status
    do 
        sudo systemctl $cmd ddns-$conf.service
        sudo systemctl $cmd ddns-$conf.timer
    done
    sudo systemctl enable ddns-$conf.timer
}

Stop() {
    conf="$1"
    Print_RED "stop ddns $conf"
    for cmd in disable stop status
    do 
        sudo systemctl $cmd ddns-$conf.timer
        sudo systemctl $cmd ddns-$conf.service
    done
}

Status() {
    conf_list=`ls /etc/ddns | grep .conf`
    
    # if there is no ddns configured
    if [ "$conf_list" = "" ];then 
        Print_RED "There is no ddns configured"
        Usage
    fi 
    
    # if have ddns client 
    for file in $conf_list
    do 
        conf=${file:0:(-5)}
        PID=`Get_PID $conf`
        echo $PID
        Print_RED "Configure: $conf"
        
        Print_RED "Service status"
        sudo systemctl status ddns-$conf.timer
        sudo systemctl status ddns-$conf.service
        
        Print_RED "DDNS status" 
        echo "PID: $PID"
        cd $working_dir
        sudo ./noip2-x86_64 -S -c $conf.conf 2>&1 | tail -n 5
    done 
}


case "$1" in
    config)
        Parameter_judge 2 $#
        Config $2
        ;;

    clean)
        Parameter_judge 2 $#
        Clean $2
        ;;

    start)
        Parameter_judge 2 $#
        Start $2
        ;;

    stop)
        Parameter_judge 2 $#
        Stop $2
        ;;

    status)
        Parameter_judge 1 $#
        Status
        ;;

    *)
        Usage
        ;;
esac
    

